server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: ll-microcloud
  company.name: www.liucanlie.com
  build.artifactId: $project.artifactId$
  build.version: $peoject.version$

zuul:
  routes:
   mydept.serviceId: microservicecloud-dept
   mydept.path: /mydept/**
  ignored-services: microservicecloud-dept
  prefix: /ll
#  ignored-services: "*"  忽略掉所有的微服务名


